body:
    - type: markdown
      attributes:
          value: |
              Hi there! 👋
              
              Thank you for using Livewire PowerGrid!
              
              Many of the people who help resolve issues here are enthusiastic PowerGrid users like yourself who volunteer their time to support fellow community members.
            
              To respect everyone's valuable time and help you resolve your issue as quickly as possible, before posting an issue, please
            
              Update to the latest version of PowerGrid by running `composer update power-components/polirium-datatable`
              Before opening a bug report, please search the existing discussions.
              
              To address this bug as fast as possible, we need the following information.
    - type: input
      id: powergrid-version
      attributes:
          label: Livewire PowerGrid version
          description: Which version of PowerGrid are you using? Please provide the full version, e.g. v6.1.0.
          placeholder: v6.1.0
      validations:
          required: true

    - type: input
      id: livewire-version
      attributes:
          label: Livewire version
          description: Which version of Livewire are you using? Please provide the full version, e.g. v3.5.16.
          placeholder: v3.5.16
      validations:
          required: true

    - type: input
      id: laravel-version
      attributes:
          label: Laravel version
          description: Which version of Laravel are you using? Please provide the full version, e.g. v11.34.2.
          placeholder: v11.34.2
      validations:
          required: true

    - type: dropdown
      id: php-version
      attributes:
          label: Which PHP version are you using?
          options:
              - PHP 8.4
              - PHP 8.3
              - PHP 8.2
              - PHP 8.1

    -   type: dropdown
        id: theme-version
        attributes:
          label: Which Theme are you using?
          options:
              - 'Tailwind'
              - 'Bootstrap 5'

    - type: dropdown
      id: published-assets
      attributes:
         label: Have you published the resource files and customized them? (php artisan vendor:publish)
         options:
            - 'Yes'
            - 'No'

      validations:
          required: true

    - type: textarea
      attributes:
          label: What is the problem?
          description: Please provide a clear and concise description of what the problem is and include screenshots.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Code snippets
          description: Please include a code snippet that we can copy and paste into our apps with steps to reproduce. Alternatively, create a public example repository and paste it here.
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              Include code snippets in triple backticks (\```) with "blade" or "php" for better readability. Here's an example:

    - type: textarea
      attributes:
          label: How do you expect it to work?
          description: Please describe how you expect it to work.
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              **We will close this issue for any of the following reasons**
              
              * The code snippets contain unrelated code such as left-over Blade variables
              * We cannot reproduce the issue with the provided code snippets
              * The issue is a duplicate

    - type: checkboxes
      attributes:
          label: Please confirm (incomplete submissions will not be addressed)
          options:
              - label: I have provided easy and step-by-step instructions to reproduce the bug.
                required: true
              - label: I have provided code samples as text and NOT images.
                required: true
              - label: I understand my bug report will be removed if I haven't met the criteria above.
                required: true

    - type: markdown
      attributes:
          value: Thank you!
